export const listImage = [
    {
        listPath: [
            "/images/4x20/1.jpg",
            "/images/4x20/4x20.jpg",
            "/images/4x20/IMG_6271.jpg",
            "/images/4x20/IMG_6274.jpg",
            "/images/4x20/IMG_6275.jpg",
        ],
        name: "Máy cấy 4 hàng x 20cm",
        infor: [
            "-Kích thước hàng cấy: 20cm",
            "-Kích thước máy: 110x100x50",
            "-Trọng lượng 35kg",
            "-Năng suất: 1080m2/h",
            "-Động cơ: xăng 4 kỳ",
            "-Xuất xứ: Việt Nam",
        ],
    },
    {
        listPath: [
            "/images/18/1.jpg",
            "/images/18/18.jpg",
            "/images/18/IMG_6246.jpg",
            "/images/18/IMG_6249.jpg",
            "/images/18/IMG_6251.jpg",
            "/images/18/IMG_6254.jpg",
        ],
        name: "Máy cấy 6 hàng x 18cm",
        infor: [
            "-Kích thước hàng cấy: 18cm",
            "-Kích thước máy: 110x126x50",
            "-Trọng lượng 56kg",
            "-Năng suất: 1080m2/h",
            "-Động cơ: xăng 4 kỳ",
            "-Xuất xứ: Việt Nam",
        ],
    },
    {
        listPath: [
            "/images/20/1.jpg",
            "/images/20/20.jpg",
            "/images/20/200.jpg",
            "/images/20/IMG_6277.jpg",
            "/images/20/IMG_6278.jpg",
            "/images/20/IMG_6280.jpg",
            "/images/20/Layer 1.jpg",
        ],
        name: "Máy cấy 6 hàng x 20cm",
        infor: [
            "-Kích thước hàng cấy: 20cm",
            "-Kích thước máy: 110x140x50",
            "-Trọng lượng 58kg",
            "-Năng suất: 1368m2/h",
            "-Động cơ: xăng 4 kỳ",
            "-Xuất xứ: Việt Nam",
        ],
    },
    {
        listPath: [
            "/images/23/1.jpg",
            "/images/23/23.jpg",
            "/images/23/IMG_6238.jpg",
            "/images/23/IMG_6239.jpg",
            "/images/23/IMG_6240.jpg",
            "/images/23/IMG_6242.jpg",
            "/images/23/IMG_6243.jpg",
        ],
        name: "Máy cấy 6 hàng x 23.5cm",
        infor: [
            "-Kích thước hàng cấy: 23.5cm",
            "-Kích thước máy: 110x165x50",
            "-Trọng lượng 64kg",
            "-Năng suất: 1620m2/h",
            "-Động cơ: xăng 4 kỳ",
            "-Xuất xứ: Việt Nam",
        ],
    },
    {
        listPath: [
            "/images/28/1.jpg",
            "/images/28/IMG_6257.jpg",
            "/images/28/IMG_6263.jpg",
            "/images/28/IMG_6265.jpg",
            "/images/28/IMG_6267.jpg",
        ],
        name: "Máy cấy 4 hàng x 28cm",
        infor: [
            "-Kích thước hàng cấy: 28cm",
            "-Kích thước máy: 110x140x50",
            "-Trọng lượng 58kg",
            "-Năng suất: 1200m2/h",
            "-Động cơ: xăng 4 kỳ",
            "-Xuất xứ: Việt Nam",
        ],
    },
];
