export const listImage = [
    {
        listPath: [
            "/images/4x20/1.png",
            "/images/4x20/4x20.JPG",
            "/images/4x20/IMG_6271.png",
            "/images/4x20/IMG_6274.png",
            "/images/4x20/IMG_6275.png",
        ],
        name: "Máy cấy 4 hàng x 20cm",
        infor: [
            "-Kích thước hàng cấy: 20cm",
            "-Kích thước máy: 110x100x50",
            "-Trọng lượng 35kg",
            "-Năng suất: 1080m2/h",
            "-Động cơ: xăng 4 kỳ",
            "-Xuất xứ: Việt Nam",
        ],
    },
    {
        listPath: [
            "/images/18/1.png",
            "/images/18/18.JPG",
            "/images/18/IMG_6246.png",
            "/images/18/IMG_6249.png",
            "/images/18/IMG_6251.png",
            "/images/18/IMG_6254.png",
        ],
        name: "Máy cấy 6 hàng x 18cm",
        infor: [
            "-Kích thước hàng cấy: 18cm",
            "-Kích thước máy: 110x126x50",
            "-Trọng lượng 56kg",
            "-Năng suất: 1080m2/h",
            "-Động cơ: xăng 4 kỳ",
            "-Xuất xứ: Việt Nam",
        ],
    },
    {
        listPath: [
            "/images/20/1.png",
            "/images/20/20.JPG",
            "/images/20/200.JPG",
            "/images/20/IMG_6277.png",
            "/images/20/IMG_6278.png",
            "/images/20/IMG_6280.png",
            "/images/20/Layer 1.png",
        ],
        name: "Máy cấy 6 hàng x 20cm",
        infor: [
            "-Kích thước hàng cấy: 20cm",
            "-Kích thước máy: 110x140x50",
            "-Trọng lượng 58kg",
            "-Năng suất: 1368m2/h",
            "-Động cơ: xăng 4 kỳ",
            "-Xuất xứ: Việt Nam",
        ],
    },
    {
        listPath: [
            "/images/23/1.png",
            "/images/23/23.JPG",
            "/images/23/IMG_6238.png",
            "/images/23/IMG_6239.png",
            "/images/23/IMG_6240.png",
            "/images/23/IMG_6242.png",
            "/images/23/IMG_6243.png",
        ],
        name: "Máy cấy 6 hàng x 23.5cm",
        infor: [
            "-Kích thước hàng cấy: 23.5cm",
            "-Kích thước máy: 110x165x50",
            "-Trọng lượng 64kg",
            "-Năng suất: 1620m2/h",
            "-Động cơ: xăng 4 kỳ",
            "-Xuất xứ: Việt Nam",
        ],
    },
    {
        listPath: [
            "/images/28/1.png",
            "/images/28/IMG_6257.png",
            "/images/28/IMG_6263.png",
            "/images/28/IMG_6265.png",
            "/images/28/IMG_6267.png",
        ],
        name: "Máy cấy 4 hàng x 28cm",
        infor: [
            "-Kích thước hàng cấy: 28cm",
            "-Kích thước máy: 110x140x50",
            "-Trọng lượng 58kg",
            "-Năng suất: 1200m2/h",
            "-Động cơ: xăng 4 kỳ",
            "-Xuất xứ: Việt Nam",
        ],
    },
];
